#!/bin/bash

exe=$(which python)
if [ "$exe" != $HOME/.virtualenvs/flask/bin/python ]; then
    echo "Must be run in 'flask' virtualenv!";
    exit 1;
fi

# this command will allow this script to be run without "./"
# export PATH=$PATH:/Users/jonahmajumder/Code/Python/server

# start Flask server

if [[ $1 == "dev" ]]; then
    echo "Starting flask server -- development version"
    export FLASK_APP=server.py
    export FLASK_ENV=development
    flask run -p 5000
elif [[ $1 == "prod" ]]; then
    echo "Starting flask server -- production version"
    gunicorn -b 0.0.0.0:5000 server:app 
else
    echo "Starting flask server -- (defaulting to) development version"
    export FLASK_APP=server.py
    export FLASK_ENV=development
    flask run -p 5000
fi
